// export const metadata = {
//   title: "Next.js",
//   description: "Generated by Next.js",
// };
import NavBar from "@/app/components/NavBar";
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      {/* <NavBar /> */}
      {children}
    </>
  );
}
